export const REQUEST_ARTICLES = "REQUEST_ARTICLES";
export const RECEIVE_ARTICLES = "RECEIVE_ARTICLES";
export const REQUEST_ARTICLE = "REQUEST_ARTICLE";
export const RECEIVE_ARTICLE = "RECEIVE_ARTICLE";

export const REQUEST_AUTHORS = "REQUEST_AUTHORS";
export const RECEIVE_AUTHORS = "RECEIVE_AUTHORS";

export const ARTICLE_CREATED = "ARTICLE_CREATED";
export const REQUEST_ARTICLE_UPDATE = "REQUEST_ARTICLE_UPDATE";
export const RECEIVE_ARTICLE_UPDATE = "RECEIVE_ARTICLE_UPDATE";
export const DELETE_ARTICLE = "DELETE_ARTICLE";

export const SET_AUTHOR = "SET_AUTHOR";
export const AUTHOR_CREATED = "AUTHOR_CREATED";

export const REQUEST_CREATE_COMMENT = "REQUEST_CREATE_COMMENT";
export const RECEIVE_NEW_COMMENT = "RECEIVE_NEW_COMMENT";
export const REQUEST_COMMENTS = "REQUEST_COMMENTS";
export const RECEIVE_COMMENTS = "RECEIVE_COMMENTS";
