export const REQUEST_ARTICLES = "REQUEST_ARTICLES";
export const RECEIVE_ARTICLES = "RECEIVE_ARTICLES";
export const REQUEST_ARTICLE = "REQUEST_ARTICLE";
export const RECEIVE_ARTICLE = "RECEIVE_ARTICLE";

export const REQUEST_AUTHORS = "REQUEST_AUTHORS";
export const RECEIVE_AUTHORS = "RECEIVE_AUTHORS";
export const AUTHOR_CREATE_REQUEST = "AUTHOR_CREATE_REQUEST";
export const RECEIVE_NEW_AUTHOR = "RECEIVE_NEW_AUTHOR";
export const SET_AUTHOR = "SET_AUTHOR";

export const ARTICLE_CREATE_REQUEST = "ARTICLE_CREATE_REQUEST";
export const ARTICLE_CREATE_RESPONSE = "ARTICLE_CREATE_RESPONSE";
export const REQUEST_ARTICLE_UPDATE = "REQUEST_ARTICLE_UPDATE";
export const RECEIVE_ARTICLE_UPDATE = "RECEIVE_ARTICLE_UPDATE";
export const ARTICLE_DELETE_REQUEST = "ARTICLE_DELETE_REQUEST";
export const ARTICLE_DELETE_RESPONSE = "ARTICLE_DELETE_RESPONSE";

export const REQUEST_CREATE_COMMENT = "REQUEST_CREATE_COMMENT";
export const RECEIVE_NEW_COMMENT = "RECEIVE_NEW_COMMENT";
export const REQUEST_COMMENTS = "REQUEST_COMMENTS";
export const RECEIVE_COMMENTS = "RECEIVE_COMMENTS";
